name: Flex
markdown: redcarpet
pygments: true
title: IndieSense Reviews
description: Candid Reviews 
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://indiesense.github.io